config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  resources :categories
  root 'snippets#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  has_many :snippets
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  include AlgoliaSearch

  validates :title, presence: true
  validates :code, presence: true

  belongs_to :category

  algoliasearch do
    attribute :title, :category_title, :description
    searchableAttributes ['title', 'category_title', 'unordered(description)']
  end

  def category_title
    category.try(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new title: ''
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to @category, notice: 'Your category was created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      redirect_to @category, notice: 'Your category was updated'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  def index
    @query = params[:q]
    if @query.blank?
      @snippets = Snippet.all.includes(:category)
    else
      @snippets = Snippet.search(@query)
    end
  end

  def new
    @snippet = Snippet.new
  end

  def create
    # Create a new model object with that data
    @snippet = Snippet.new(snippet_params)
    # Attempt to save that model to the database
    if @snippet.save
      # If saved, then redirect to that snippet’s page
      redirect_to @snippet, notice: 'Your snippet was created'
    else
      # Otherwise, show the user the form again with errors
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    # Update model object with that data
    if @snippet.update_attributes(snippet_params)
      # If saved, then redirect to that snippet’s page
      redirect_to @snippet, notice: 'Your snippet was updated'
    else
      # Otherwise, show the user the form again with errors
      render :edit
    end
  end

  def destroy
    @snippet.destroy
  end

  private
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Get the submitted form data from params
    def snippet_params
      params.require(:snippet).permit(:title, :description, :code, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% category.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <%= f.submit %>
<% end %>

app/views/categories/_nav.html.erb
<nav>
  <section>
    <%= link_to_unless_current 'Snippets', controller: :snippets, action: :index %> ·
    <%= link_to_unless_current 'Categories', action: :index %> ·
    <%= link_to_unless_current 'New category', action: :new %>
  </section>
  <% if local_assigns.include? :category %>
    <section>
        <%= link_to_unless_current 'View', id: category, action: :show %> ·
        <%= link_to_unless_current 'Edit', id: category, action: :edit %> ·
        <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are your sure you want to delete this category?' } %>
    </section>
  <% end %>
</nav>

app/views/categories/edit.html.erb
<%= render 'nav', category: @category %>

<section>
  <%= render 'form', category: @category %>
</section>

app/views/categories/index.html.erb
<%= render 'nav' %>

<section>
  <% @categories.each do |category| %>
    <article>
      <h2><%= link_to category.title, category %></h2>
      <%= link_to 'Edit', edit_category_path(category) %>
    </article>
  <% end %>
</section>

app/views/categories/new.html.erb
<%= render 'nav' %>

<section>
  <%= render 'form', category: @category %>
</section>

app/views/categories/show.html.erb
<%= render 'nav', category: @category %>

<section>
  <h1><%= @category.title %></h1>
</section>

<section>
  <% @category.snippets.each do |snippet| %>
    <article>
      <%= render snippet, short: true %>
    </article>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snippy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/highlight.min.js' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.11.0/styles/monokai-sublime.min.css' %>
    <script>
      document.addEventListener("turbolinks:load", function() {
        $('pre code').each(function(i, e) { hljs.highlightBlock(e) });
      })
    </script>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(snippet) do |f| %>
  <% snippet.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :title, prompt: 'Choose a category' %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description, cols: 30 %>
  </div>

  <div>
    <%= f.label :code %>
    <%= f.text_area :code, cols: 30, rows: 10 %>
  </div>

  <%= f.submit %>
<% end %>

app/views/snippets/_nav.html.erb
<nav>
  <section>
    <%= link_to_unless_current 'Snippets', action: :index %> ·
    <%= link_to_unless_current 'Categories', controller: :categories, action: :index %> ·
    <%= link_to_unless_current 'New snippet', action: :new %>
  </section>
  <% if local_assigns.include? :snippet %>
    <section>
        <%= link_to_unless_current 'View', id: snippet, action: :show %> ·
        <%= link_to_unless_current 'Edit', id: snippet, action: :edit %> ·
        <%= link_to 'Delete', snippet, method: :delete, data: { confirm: 'Are your sure you want to delete this snippet?' } %>
    </section>
  <% end %>
</nav>

app/views/snippets/_snippet.html.erb
<% short = local_assigns.fetch(:short, false) %>

<div>
  <h2><%= link_to snippet.title, snippet %></h2>
  <% if snippet.category.present? %>
    <h3>
      <%= short ? '' : 'Category: ' %>
      <%= link_to snippet.category.try(:title), snippet.category %>
    </h3>
  <% end %>
  <% unless short %>
    <%= simple_format snippet.description %>
    <h3>Code:</h3>
  <% end %>
  <pre><code><%= snippet.code %></code></pre>
  <% if short %>
    <%= link_to 'Edit', edit_snippet_path(snippet) %>
  <% end %>
</div>

app/views/snippets/edit.html.erb
<%= render 'nav', snippet: @snippet %>

<section>
  <%= render 'form', snippet: @snippet %>
</section>

app/views/snippets/index.html.erb
<%= render 'nav' %>

<section>
  <%= form_tag './', method: :get do %>
    <% search_field_tag :q, @query, placeholder: 'Search' %>
  <% end %>
</section>

<section>
  <% if @snippets.empty? %>
    <% if @query.present? %>
      <h2>No snippets found for '<%= @query %>'</h2>
    <% else %>
      <h2>No snippets</h2>
    <% end %>
  <% else %>
    <% @snippets.each do |snippet| %>
      <article>
        <%= render snippet, short: true %>
      </article>
    <% end %>
  <% end %>
</section>

app/views/snippets/new.html.erb
<%= render 'nav' %>

<section>
  <%= render 'form', snippet: @snippet %>
</section>

app/views/snippets/show.html.erb
<%= render 'nav', snippet: @snippet %>

<section>
  <%= render @snippet %>
</section>